# Generated by Django 5.0.6 on 2024-06-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestform',
            name='approved',
            field=models.CharField(choices=[('Review', 'Review'), ('Permitted', 'Permitted'), ('Denied', 'Denied')], default='Review', max_length=10, verbose_name='For approval'),
        ),
    ]
